### ISSUE TITLE
Option To Disable Speaker Audio From Self

### ISSUE THREAD

**Issue by aybri** [SwitchCraftCC/Plethora-Fabric#36]
So, with the power of arbitrary audio through speakers, players have done some amazing things. Songs, TTS, you name it... However, when it comes to neural implants, *you can hear the audio from it yourself.*

That's not necessarily a bad thing, though. Sometimes you may want to hear the audio coming from your neural implant. However, sometimes, like if I'm streaming my real microphone to it and I would rather not hear the feedback, it's obviously unwanted.

So here's my solution. Simply add an option in Plethora's Mod Menu settings that can toggle hearing audio from your own neural implant. I'm unsure how feasible it is, but I'm hoping it's possible.

**Comment by Lemmmy** [comment]
At the moment CC: Tweaked speaker packets send the [entity responsible for the sound](https://github.com/cc-tweaked/CC-Tweaked/blob/e2cf43718f0657d984c05cb9d1f7fb9e5888553c/projects/common/src/main/java/dan200/computercraft/shared/peripheral/speaker/SpeakerPosition.java#LL38), but nothing to differentiate what item/computer was actually responsible for the sound. Meaning, from a networking point of view, a Neural Interface making sound and a Pocket Computer making sound are indistinguishable. Because of that, this might be a feature request better suited for CC.

In terms of feasibility, Plethora can still implement this, but it would affect Pocket Computers too. I'm not sure how I would feel about a Plethora setting changing CC:T behavior.

**Comment by Lemmmy** [comment]
Thanks for your feature request. I may still consider it in the future, but since this would introduce behavior inconsistent with CC:T, I do think this request is better suited for there.
