### ISSUE TITLE
[Request] Backport to 1.19.2

### ISSUE THREAD

**Issue by LunaFolf** [SwitchCraftCC/Plethora-Fabric#42]
A number of mods are still on 1.19.2 and are either still in the process of being updated, or won't be updated.

I myself tried to update my pack to 1.19.3 so I could add Plethora, but unfortunately we would loose too many essential mods in doing so.

**Comment by Kan18** [comment]
I think that backporting the mod now is unlikely to happen, but you could try building the mod yourself using its source before it was updated to 1.19.3: https://github.com/SwitchCraftCC/Plethora-Fabric/commit/dd30866b41ee3ed559a6f9f0819807de1d98f388

**Comment by LunaFolf** [comment]
If I was to rebuild a previous commit, I'd have to provide the mod jar manually in my modpack rather than using curseforge - would that be allowed?

I'll try rebuild it this afternoon although I'm not a Java dev so it'll take me some time to figure it out.

**Comment by SquidDev** [comment]
Yep, as long as you follow the license you're allowed to redistribute modified versions. Though obviously you're going to get any official support - there's been a lot of bugfixes since the 1.19.3 update.

The main problem with 1.19.2 is that you need to use CC: Restitched, which has several API differences compared with CC:T (which is only available for 1.19.3). You'd also need to revert https://github.com/SwitchCraftCC/Plethora-Fabric/commit/15e3497d0693fd38bdec53340b6ef08265743e48, and possibly some other later commits.
