### ISSUE TITLE
Add Plethora metadata for Item Magnets

### ISSUE THREAD

**Issue by znepb** [SwitchCraftCC/Plethora-Fabric#90]
I'm suggesting chat messages be sent for updates with the item magnet, such as toggle notifications, and low charge notifications. I can make a PR if this suggestion is approved.

**Comment by Lemmmy** [comment]
I think a better approach would be to make sure Plethora can read magnet information (it can get the damage, but can it access Trinkets slots via getEquipment?) and then the user can set up whatever notifications they want.

**Comment by Kan18** [comment]
Plethora can get metadata from Trinkets slots (via `getMetaOwner`, etc.) since https://github.com/SwitchCraftCC/Plethora-Fabric/commit/d9683ca76b863a972d5897d414ea7215fac52d0d 
<img width="486" alt="image" src="https://github.com/SwitchCraftCC/sc-goodies/assets/24967425/5b900350-f96d-4c3a-a757-381e9e8e49ef">

**Comment by Lemmmy** [comment]
Closed by 64fbf40bedcdc24a065b9acd003424069484f3d3
